### PR TITLE
Join exclude_tags to properly set noindent_tags

### PR DESCRIPTION
**Pull request by nhooyr**
As the title says. Latest commit forgot about this.

### CODE REVIEW

**Comment by dmitrivereshchagin** [comment]
:+1:

**Comment by nhooyr** [comment]
@othree could you please merge it :P

**Comment by othree** [comment]
Thank you :+1:

**Comment by othree** [comment]
I think it require some test to see is exclude tag empty.
If not, do the join
If empty, do nothing.

**Comment by nhooyr** [comment]
@othree it works fine if exclude_tag is empty, I tested that.

**Pull request merged**
