### PR TITLE
replace syntax ` to $( )

### PR DESCRIPTION
**Pull request by sagax**
i think this style to be better

### CODE REVIEW

**Comment by othree** [comment]
Is there any comparison of these two syntax?

**Comment by sagax** [comment]
construction ` ` and $ () are identical. but the $ () is best read

**Comment by sagax** [comment]
example

``` bash
echo `echo `ls`` # INCORRECT
echo `echo \`ls\`` # CORRECT
echo $(echo $(ls)) # CORRECT
```

**Comment by othree** [comment]
You convinced me.
But I found this file is from [vim-makefile](https://github.com/c9s/vim-makefile).
You should report to @c9s

**Pull request closed without merging**
